### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by qianxi0410** [diy4869/diy4869#1]
你好，看起来你似乎是对我主页的snake图片感兴趣，但是你这里好像引用成我的了，你应该将将GitHub action换成你自己的。
可以见我的博客 https://blog.qianx1.xyz/post/snake-your-github-profile

**Comment by diy4869** [comment]
抱歉，是从您配吗这个仓库点进来的，看到这个贪吃蛇的游戏动图，感觉比较有意思，就加了上去，这个博客的链接好像打不开的样子。

**Comment by qianxi0410** [comment]
> 抱歉，是从您配吗这个仓库点进来的，看到这个贪吃蛇的游戏动图，感觉比较有意思，就加了上去，这个博客的链接好像打不开的样子。

现在在试试呢。没啥道歉的，只是看到了提醒一下捏。

**Comment by qianxi0410** [comment]
> > 抱歉，是从您配吗这个仓库点进来的，看到这个贪吃蛇的游戏动图，感觉比较有意思，就加了上去，这个博客的链接好像打不开的样子。
> 
> 现在在试试呢。没啥道歉的，只是看到了提醒一下捏。

好像不能直接访问，需要blog.qianx1.xyz 从首页进去（逻辑有问题，是我太菜了

**Comment by diy4869** [comment]
thanks，现在好了

**Comment by qianxi0410** [comment]
:D
